### ISSUE TITLE
info/question about clusters

### ISSUE THREAD

**Issue by giuliohome** [glenbraun/FlowSharp#1]
My still unanswered question when I read about workflows and schedulers: how to set up it on multiple application servers? my goals would be to accomplish both failover and round-robin at a basic level: does it make sense? Is that feasible, also on premises?

**Comment by glenbraun** [comment]
Sorry to miss your question. 

Yes, it makes sense to run both deciders and activity running processes on many different hosts. There shouldn't be a need for failover or round-robin because SWF will assign tasks, probably on a first come, first served basis but I'm not sure on that. Regardless, if one processes were busy computing a decision and another process was polling, waiting for a task, SWF will assign the task to the process that's polling. You can use TaskLists for priority queues or other logic to partition task assignment.

The FsDecider framework specifically focuses on writing the decider logic and not on other aspects of an SWF solution like: registering workflow and activity types, starting workflows, permissions, or managing hosts running decider and activity processes. Those could be useful things to include in a generalized solution but I didn't want to make assumptions about the architecture of the SWF solution. For instance, I think a strength of SWF is that activity task handlers could be written in any language which can access the SWF web API (i.e., Java, Python, etc.). Since FsDecider is specifically for deciders written in F#, I didn't want to impose a design dependency or assumption which required writing the rest of the SWF solution in F# too.

I'd be happy to discuss with you my thoughts related to what you're trying to do.

**Comment by giuliohome** [comment]
Excellent reply which completely answers my questions about _FsDecider_ . 
Yes, indeed I had some doubts about how SWF assigns tasks, but it's another topic.
I think we can close this for the moment since you clarified very well what _this framework_  focuses on.
Thank you very much.
